name: Build on tag

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-*

jobs:
  build:
    name: Build image
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set env variables
        run: |
          echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
          IMAGE_NAME="${GITHUB_REPOSITORY#*/}"
          echo "IMAGE_NAME=${IMAGE_NAME//docker-/}" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        id: qemu

      - name: Setup Docker buildx action
        uses: docker/setup-buildx-action@v2
        id: buildx

      - name: Run Docker buildx
        run: |
          docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --no-cache -t niteshbalusu/lndboss:$TAG --push .
